/**
 * Unified Error Codes for Auricapri Frontend
 *
 * These codes match backend error codes for consistency across the platform.
 */

export enum ErrorCode {
  // Generic Errors
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  MAINTENANCE_MODE = 'MAINTENANCE_MODE',
  INVALID_REQUEST = 'INVALID_REQUEST',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',

  // Authentication Errors
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
  AUTH_EMAIL_NOT_CONFIRMED = 'AUTH_EMAIL_NOT_CONFIRMED',
  AUTH_USER_DISABLED = 'AUTH_USER_DISABLED',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_OAUTH_FAILED = 'AUTH_OAUTH_FAILED',
  AUTH_MFA_REQUIRED = 'AUTH_MFA_REQUIRED',
  AUTH_MFA_INVALID = 'AUTH_MFA_INVALID',
  AUTH_PASSWORD_WEAK = 'AUTH_PASSWORD_WEAK',
  AUTH_PASSWORD_RESET_EXPIRED = 'AUTH_PASSWORD_RESET_EXPIRED',

  // Authorization Errors
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  RESOURCE_ACCESS_DENIED = 'RESOURCE_ACCESS_DENIED',
  ADMIN_ONLY = 'ADMIN_ONLY',
  OWNER_ONLY = 'OWNER_ONLY',

  // User Errors
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_EMAIL_IN_USE = 'USER_EMAIL_IN_USE',
  USER_PHONE_IN_USE = 'USER_PHONE_IN_USE',
  USER_CPF_IN_USE = 'USER_CPF_IN_USE',
  USER_INVALID_CPF = 'USER_INVALID_CPF',
  USER_PROFILE_INCOMPLETE = 'USER_PROFILE_INCOMPLETE',
  USER_ADDRESS_NOT_FOUND = 'USER_ADDRESS_NOT_FOUND',
  USER_ADDRESS_INVALID = 'USER_ADDRESS_INVALID',

  // Product Errors
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_INACTIVE = 'PRODUCT_INACTIVE',
  PRODUCT_OUT_OF_STOCK = 'PRODUCT_OUT_OF_STOCK',
  PRODUCT_VARIANT_NOT_FOUND = 'PRODUCT_VARIANT_NOT_FOUND',
  PRODUCT_VARIANT_INACTIVE = 'PRODUCT_VARIANT_INACTIVE',
  PRODUCT_INVALID_PRICE = 'PRODUCT_INVALID_PRICE',
  PRODUCT_INVALID_STOCK = 'PRODUCT_INVALID_STOCK',
  PRODUCT_SKU_DUPLICATE = 'PRODUCT_SKU_DUPLICATE',
  PRODUCT_IMAGE_UPLOAD_FAILED = 'PRODUCT_IMAGE_UPLOAD_FAILED',
  PRODUCT_CATEGORY_NOT_FOUND = 'PRODUCT_CATEGORY_NOT_FOUND',
  PRODUCT_COLLECTION_NOT_FOUND = 'PRODUCT_COLLECTION_NOT_FOUND',

  // Cart Errors
  CART_EMPTY = 'CART_EMPTY',
  CART_ITEM_NOT_FOUND = 'CART_ITEM_NOT_FOUND',
  CART_ITEM_QUANTITY_INVALID = 'CART_ITEM_QUANTITY_INVALID',
  CART_ITEM_EXCEEDS_STOCK = 'CART_ITEM_EXCEEDS_STOCK',
  CART_ITEM_PRICE_CHANGED = 'CART_ITEM_PRICE_CHANGED',
  CART_SYNC_FAILED = 'CART_SYNC_FAILED',
  CART_MERGE_FAILED = 'CART_MERGE_FAILED',

  // Order Errors
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_ALREADY_CANCELLED = 'ORDER_ALREADY_CANCELLED',
  ORDER_CANNOT_BE_CANCELLED = 'ORDER_CANNOT_BE_CANCELLED',
  ORDER_INVALID_STATUS_TRANSITION = 'ORDER_INVALID_STATUS_TRANSITION',
  ORDER_ITEMS_UNAVAILABLE = 'ORDER_ITEMS_UNAVAILABLE',
  ORDER_MINIMUM_NOT_MET = 'ORDER_MINIMUM_NOT_MET',
  ORDER_ADDRESS_REQUIRED = 'ORDER_ADDRESS_REQUIRED',
  ORDER_SHIPPING_REQUIRED = 'ORDER_SHIPPING_REQUIRED',
  ORDER_REVIEW_NOT_FOUND = 'ORDER_REVIEW_NOT_FOUND',
  ORDER_ALREADY_REVIEWED = 'ORDER_ALREADY_REVIEWED',
  ORDER_TRACKING_UNAVAILABLE = 'ORDER_TRACKING_UNAVAILABLE',

  // Payment Errors
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_DECLINED = 'PAYMENT_DECLINED',
  PAYMENT_CARD_INVALID = 'PAYMENT_CARD_INVALID',
  PAYMENT_CARD_EXPIRED = 'PAYMENT_CARD_EXPIRED',
  PAYMENT_INSUFFICIENT_FUNDS = 'PAYMENT_INSUFFICIENT_FUNDS',
  PAYMENT_FRAUD_DETECTED = 'PAYMENT_FRAUD_DETECTED',
  PAYMENT_GATEWAY_ERROR = 'PAYMENT_GATEWAY_ERROR',
  PAYMENT_PIX_EXPIRED = 'PAYMENT_PIX_EXPIRED',
  PAYMENT_BOLETO_EXPIRED = 'PAYMENT_BOLETO_EXPIRED',
  PAYMENT_REFUND_FAILED = 'PAYMENT_REFUND_FAILED',
  PAYMENT_METHOD_UNAVAILABLE = 'PAYMENT_METHOD_UNAVAILABLE',

  // Coupon Errors
  COUPON_NOT_FOUND = 'COUPON_NOT_FOUND',
  COUPON_EXPIRED = 'COUPON_EXPIRED',
  COUPON_INACTIVE = 'COUPON_INACTIVE',
  COUPON_ALREADY_USED = 'COUPON_ALREADY_USED',
  COUPON_MINIMUM_NOT_MET = 'COUPON_MINIMUM_NOT_MET',
  COUPON_PRODUCT_NOT_ELIGIBLE = 'COUPON_PRODUCT_NOT_ELIGIBLE',
  COUPON_USAGE_LIMIT_REACHED = 'COUPON_USAGE_LIMIT_REACHED',
  COUPON_CODE_DUPLICATE = 'COUPON_CODE_DUPLICATE',

  // Shipping/Delivery Errors
  SHIPPING_ADDRESS_INVALID = 'SHIPPING_ADDRESS_INVALID',
  SHIPPING_CEP_NOT_FOUND = 'SHIPPING_CEP_NOT_FOUND',
  SHIPPING_AREA_NOT_COVERED = 'SHIPPING_AREA_NOT_COVERED',
  SHIPPING_QUOTE_FAILED = 'SHIPPING_QUOTE_FAILED',
  SHIPPING_CARRIER_UNAVAILABLE = 'SHIPPING_CARRIER_UNAVAILABLE',
  SHIPPING_LABEL_GENERATION_FAILED = 'SHIPPING_LABEL_GENERATION_FAILED',
  SHIPPING_TRACKING_UNAVAILABLE = 'SHIPPING_TRACKING_UNAVAILABLE',
  DELIVERY_ASSIGNMENT_FAILED = 'DELIVERY_ASSIGNMENT_FAILED',

  // Review Errors
  REVIEW_NOT_FOUND = 'REVIEW_NOT_FOUND',
  REVIEW_ALREADY_EXISTS = 'REVIEW_ALREADY_EXISTS',
  REVIEW_NOT_ELIGIBLE = 'REVIEW_NOT_ELIGIBLE',
  REVIEW_RATING_INVALID = 'REVIEW_RATING_INVALID',
  REVIEW_CONTENT_INVALID = 'REVIEW_CONTENT_INVALID',
  REVIEW_MEDIA_UPLOAD_FAILED = 'REVIEW_MEDIA_UPLOAD_FAILED',

  // Loyalty Errors
  LOYALTY_NOT_ENABLED = 'LOYALTY_NOT_ENABLED',
  LOYALTY_INSUFFICIENT_POINTS = 'LOYALTY_INSUFFICIENT_POINTS',
  LOYALTY_CASHBACK_UNAVAILABLE = 'LOYALTY_CASHBACK_UNAVAILABLE',
  LOYALTY_REWARD_NOT_FOUND = 'LOYALTY_REWARD_NOT_FOUND',
  LOYALTY_REWARD_EXPIRED = 'LOYALTY_REWARD_EXPIRED',

  // External Service Errors
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  SUPABASE_ERROR = 'SUPABASE_ERROR',
  REDIS_ERROR = 'REDIS_ERROR',
  PAYMENT_GATEWAY_TIMEOUT = 'PAYMENT_GATEWAY_TIMEOUT',
  SHIPPING_API_ERROR = 'SHIPPING_API_ERROR',
  GEOCODING_ERROR = 'GEOCODING_ERROR',

  // File/Storage Errors
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED = 'FILE_TYPE_NOT_ALLOWED',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
  STORAGE_QUOTA_EXCEEDED = 'STORAGE_QUOTA_EXCEEDED',

  // Network Errors (Client-side only)
  NETWORK_ERROR = 'NETWORK_ERROR',
  CONNECTION_TIMEOUT = 'CONNECTION_TIMEOUT',
  NO_INTERNET = 'NO_INTERNET',
}

export enum ErrorCategory {
  NETWORK = 'network',
  AUTH = 'auth',
  AUTHORIZATION = 'authorization',
  VALIDATION = 'validation',
  NOT_FOUND = 'not_found',
  CONFLICT = 'conflict',
  SERVER = 'server',
  STORAGE = 'storage',
  PAYMENT = 'payment',
  SHIPPING = 'shipping',
  EXTERNAL = 'external',
  UNKNOWN = 'unknown',
}

export const ErrorCodeToCategory: Record<ErrorCode, ErrorCategory> = {
  // Network
  [ErrorCode.NETWORK_ERROR]: ErrorCategory.NETWORK,
  [ErrorCode.CONNECTION_TIMEOUT]: ErrorCategory.NETWORK,
  [ErrorCode.NO_INTERNET]: ErrorCategory.NETWORK,

  // Auth
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: ErrorCategory.AUTH,
  [ErrorCode.AUTH_TOKEN_EXPIRED]: ErrorCategory.AUTH,
  [ErrorCode.AUTH_TOKEN_INVALID]: ErrorCategory.AUTH,
  [ErrorCode.AUTH_TOKEN_MISSING]: ErrorCategory.AUTH,
  [ErrorCode.AUTH_EMAIL_NOT_CONFIRMED]: ErrorCategory.AUTH,
  [ErrorCode.AUTH_USER_DISABLED]: ErrorCategory.AUTH,
  [ErrorCode.AUTH_SESSION_EXPIRED]: ErrorCategory.AUTH,
  [ErrorCode.AUTH_OAUTH_FAILED]: ErrorCategory.AUTH,
  [ErrorCode.AUTH_MFA_REQUIRED]: ErrorCategory.AUTH,
  [ErrorCode.AUTH_MFA_INVALID]: ErrorCategory.AUTH,
  [ErrorCode.AUTH_PASSWORD_WEAK]: ErrorCategory.VALIDATION,
  [ErrorCode.AUTH_PASSWORD_RESET_EXPIRED]: ErrorCategory.AUTH,

  // Authorization
  [ErrorCode.FORBIDDEN]: ErrorCategory.AUTHORIZATION,
  [ErrorCode.INSUFFICIENT_PERMISSIONS]: ErrorCategory.AUTHORIZATION,
  [ErrorCode.RESOURCE_ACCESS_DENIED]: ErrorCategory.AUTHORIZATION,
  [ErrorCode.ADMIN_ONLY]: ErrorCategory.AUTHORIZATION,
  [ErrorCode.OWNER_ONLY]: ErrorCategory.AUTHORIZATION,

  // Not Found
  [ErrorCode.NOT_FOUND]: ErrorCategory.NOT_FOUND,
  [ErrorCode.USER_NOT_FOUND]: ErrorCategory.NOT_FOUND,
  [ErrorCode.USER_ADDRESS_NOT_FOUND]: ErrorCategory.NOT_FOUND,
  [ErrorCode.PRODUCT_NOT_FOUND]: ErrorCategory.NOT_FOUND,
  [ErrorCode.PRODUCT_VARIANT_NOT_FOUND]: ErrorCategory.NOT_FOUND,
  [ErrorCode.PRODUCT_CATEGORY_NOT_FOUND]: ErrorCategory.NOT_FOUND,
  [ErrorCode.PRODUCT_COLLECTION_NOT_FOUND]: ErrorCategory.NOT_FOUND,
  [ErrorCode.CART_ITEM_NOT_FOUND]: ErrorCategory.NOT_FOUND,
  [ErrorCode.ORDER_NOT_FOUND]: ErrorCategory.NOT_FOUND,
  [ErrorCode.ORDER_REVIEW_NOT_FOUND]: ErrorCategory.NOT_FOUND,
  [ErrorCode.COUPON_NOT_FOUND]: ErrorCategory.NOT_FOUND,
  [ErrorCode.SHIPPING_CEP_NOT_FOUND]: ErrorCategory.NOT_FOUND,
  [ErrorCode.REVIEW_NOT_FOUND]: ErrorCategory.NOT_FOUND,
  [ErrorCode.LOYALTY_REWARD_NOT_FOUND]: ErrorCategory.NOT_FOUND,

  // Conflict
  [ErrorCode.USER_ALREADY_EXISTS]: ErrorCategory.CONFLICT,
  [ErrorCode.USER_EMAIL_IN_USE]: ErrorCategory.CONFLICT,
  [ErrorCode.USER_PHONE_IN_USE]: ErrorCategory.CONFLICT,
  [ErrorCode.USER_CPF_IN_USE]: ErrorCategory.CONFLICT,
  [ErrorCode.PRODUCT_SKU_DUPLICATE]: ErrorCategory.CONFLICT,
  [ErrorCode.CART_ITEM_PRICE_CHANGED]: ErrorCategory.CONFLICT,
  [ErrorCode.ORDER_ALREADY_REVIEWED]: ErrorCategory.CONFLICT,
  [ErrorCode.COUPON_CODE_DUPLICATE]: ErrorCategory.CONFLICT,
  [ErrorCode.REVIEW_ALREADY_EXISTS]: ErrorCategory.CONFLICT,

  // Payment
  [ErrorCode.PAYMENT_FAILED]: ErrorCategory.PAYMENT,
  [ErrorCode.PAYMENT_DECLINED]: ErrorCategory.PAYMENT,
  [ErrorCode.PAYMENT_CARD_INVALID]: ErrorCategory.PAYMENT,
  [ErrorCode.PAYMENT_CARD_EXPIRED]: ErrorCategory.PAYMENT,
  [ErrorCode.PAYMENT_INSUFFICIENT_FUNDS]: ErrorCategory.PAYMENT,
  [ErrorCode.PAYMENT_FRAUD_DETECTED]: ErrorCategory.PAYMENT,
  [ErrorCode.PAYMENT_PIX_EXPIRED]: ErrorCategory.PAYMENT,
  [ErrorCode.PAYMENT_BOLETO_EXPIRED]: ErrorCategory.PAYMENT,
  [ErrorCode.PAYMENT_REFUND_FAILED]: ErrorCategory.PAYMENT,
  [ErrorCode.PAYMENT_METHOD_UNAVAILABLE]: ErrorCategory.PAYMENT,

  // Shipping
  [ErrorCode.SHIPPING_ADDRESS_INVALID]: ErrorCategory.SHIPPING,
  [ErrorCode.SHIPPING_AREA_NOT_COVERED]: ErrorCategory.SHIPPING,
  [ErrorCode.SHIPPING_LABEL_GENERATION_FAILED]: ErrorCategory.SHIPPING,
  [ErrorCode.DELIVERY_ASSIGNMENT_FAILED]: ErrorCategory.SHIPPING,

  // Storage
  [ErrorCode.PRODUCT_IMAGE_UPLOAD_FAILED]: ErrorCategory.STORAGE,
  [ErrorCode.FILE_UPLOAD_FAILED]: ErrorCategory.STORAGE,
  [ErrorCode.STORAGE_QUOTA_EXCEEDED]: ErrorCategory.STORAGE,
  [ErrorCode.REVIEW_MEDIA_UPLOAD_FAILED]: ErrorCategory.STORAGE,
  [ErrorCode.FILE_TOO_LARGE]: ErrorCategory.STORAGE,
  [ErrorCode.FILE_TYPE_NOT_ALLOWED]: ErrorCategory.STORAGE,

  // External
  [ErrorCode.EXTERNAL_SERVICE_ERROR]: ErrorCategory.EXTERNAL,
  [ErrorCode.SUPABASE_ERROR]: ErrorCategory.EXTERNAL,
  [ErrorCode.PAYMENT_GATEWAY_ERROR]: ErrorCategory.EXTERNAL,
  [ErrorCode.PAYMENT_GATEWAY_TIMEOUT]: ErrorCategory.EXTERNAL,
  [ErrorCode.SHIPPING_API_ERROR]: ErrorCategory.EXTERNAL,
  [ErrorCode.SHIPPING_QUOTE_FAILED]: ErrorCategory.EXTERNAL,
  [ErrorCode.SHIPPING_CARRIER_UNAVAILABLE]: ErrorCategory.EXTERNAL,
  [ErrorCode.GEOCODING_ERROR]: ErrorCategory.EXTERNAL,
  [ErrorCode.SHIPPING_TRACKING_UNAVAILABLE]: ErrorCategory.EXTERNAL,

  // Server
  [ErrorCode.INTERNAL_SERVER_ERROR]: ErrorCategory.SERVER,
  [ErrorCode.SERVICE_UNAVAILABLE]: ErrorCategory.SERVER,
  [ErrorCode.RATE_LIMIT_EXCEEDED]: ErrorCategory.SERVER,
  [ErrorCode.MAINTENANCE_MODE]: ErrorCategory.SERVER,
  [ErrorCode.REDIS_ERROR]: ErrorCategory.SERVER,
  [ErrorCode.CART_SYNC_FAILED]: ErrorCategory.SERVER,
  [ErrorCode.CART_MERGE_FAILED]: ErrorCategory.SERVER,

  // Validation (default for remaining)
  [ErrorCode.UNKNOWN_ERROR]: ErrorCategory.UNKNOWN,
  [ErrorCode.INVALID_REQUEST]: ErrorCategory.VALIDATION,
  [ErrorCode.VALIDATION_ERROR]: ErrorCategory.VALIDATION,
  [ErrorCode.USER_INVALID_CPF]: ErrorCategory.VALIDATION,
  [ErrorCode.USER_PROFILE_INCOMPLETE]: ErrorCategory.VALIDATION,
  [ErrorCode.USER_ADDRESS_INVALID]: ErrorCategory.VALIDATION,
  [ErrorCode.PRODUCT_INACTIVE]: ErrorCategory.VALIDATION,
  [ErrorCode.PRODUCT_OUT_OF_STOCK]: ErrorCategory.VALIDATION,
  [ErrorCode.PRODUCT_VARIANT_INACTIVE]: ErrorCategory.VALIDATION,
  [ErrorCode.PRODUCT_INVALID_PRICE]: ErrorCategory.VALIDATION,
  [ErrorCode.PRODUCT_INVALID_STOCK]: ErrorCategory.VALIDATION,
  [ErrorCode.CART_EMPTY]: ErrorCategory.VALIDATION,
  [ErrorCode.CART_ITEM_QUANTITY_INVALID]: ErrorCategory.VALIDATION,
  [ErrorCode.CART_ITEM_EXCEEDS_STOCK]: ErrorCategory.VALIDATION,
  [ErrorCode.ORDER_ALREADY_CANCELLED]: ErrorCategory.VALIDATION,
  [ErrorCode.ORDER_CANNOT_BE_CANCELLED]: ErrorCategory.VALIDATION,
  [ErrorCode.ORDER_INVALID_STATUS_TRANSITION]: ErrorCategory.VALIDATION,
  [ErrorCode.ORDER_ITEMS_UNAVAILABLE]: ErrorCategory.VALIDATION,
  [ErrorCode.ORDER_MINIMUM_NOT_MET]: ErrorCategory.VALIDATION,
  [ErrorCode.ORDER_ADDRESS_REQUIRED]: ErrorCategory.VALIDATION,
  [ErrorCode.ORDER_SHIPPING_REQUIRED]: ErrorCategory.VALIDATION,
  [ErrorCode.ORDER_TRACKING_UNAVAILABLE]: ErrorCategory.VALIDATION,
  [ErrorCode.COUPON_EXPIRED]: ErrorCategory.VALIDATION,
  [ErrorCode.COUPON_INACTIVE]: ErrorCategory.VALIDATION,
  [ErrorCode.COUPON_ALREADY_USED]: ErrorCategory.VALIDATION,
  [ErrorCode.COUPON_MINIMUM_NOT_MET]: ErrorCategory.VALIDATION,
  [ErrorCode.COUPON_PRODUCT_NOT_ELIGIBLE]: ErrorCategory.VALIDATION,
  [ErrorCode.COUPON_USAGE_LIMIT_REACHED]: ErrorCategory.VALIDATION,
  [ErrorCode.REVIEW_NOT_ELIGIBLE]: ErrorCategory.AUTHORIZATION,
  [ErrorCode.REVIEW_RATING_INVALID]: ErrorCategory.VALIDATION,
  [ErrorCode.REVIEW_CONTENT_INVALID]: ErrorCategory.VALIDATION,
  [ErrorCode.LOYALTY_NOT_ENABLED]: ErrorCategory.VALIDATION,
  [ErrorCode.LOYALTY_INSUFFICIENT_POINTS]: ErrorCategory.VALIDATION,
  [ErrorCode.LOYALTY_CASHBACK_UNAVAILABLE]: ErrorCategory.VALIDATION,
  [ErrorCode.LOYALTY_REWARD_EXPIRED]: ErrorCategory.VALIDATION,
};

export function getErrorCategory(code: ErrorCode): ErrorCategory {
  return ErrorCodeToCategory[code] || ErrorCategory.UNKNOWN;
}

export function isAuthError(code: ErrorCode): boolean {
  return code.startsWith('AUTH_');
}

export function isNetworkError(code: ErrorCode): boolean {
  return [
    ErrorCode.NETWORK_ERROR,
    ErrorCode.CONNECTION_TIMEOUT,
    ErrorCode.NO_INTERNET,
    ErrorCode.SERVICE_UNAVAILABLE,
  ].includes(code);
}

export function isRetryableError(code: ErrorCode): boolean {
  return [
    ErrorCode.SERVICE_UNAVAILABLE,
    ErrorCode.RATE_LIMIT_EXCEEDED,
    ErrorCode.EXTERNAL_SERVICE_ERROR,
    ErrorCode.PAYMENT_GATEWAY_ERROR,
    ErrorCode.PAYMENT_GATEWAY_TIMEOUT,
    ErrorCode.SHIPPING_API_ERROR,
    ErrorCode.NETWORK_ERROR,
    ErrorCode.CONNECTION_TIMEOUT,
  ].includes(code);
}
